apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-material
spec:
  displayName: Vite Starter
  author:
    name: Halo
    website: https://github.com/Anyexyz
  description: A development starter theme with Vite Ecosystem for Halo
  logo: https://www.halo.run/logo
  homepage: https://github.com/Anyexyz/theme-material#readme
  repo: https://github.com/Anyexyz/theme-material
  issues: https://github.com/Anyexyz/theme-material/issues
  settingName: "theme-material-setting"
  configMapName: "theme-material-configMap"
  version: 1.0.0
  requires: ">=2.0.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Anyexyz/theme-material/blob/main/LICENSE"
