apiVersion: theme.halo.run/v1alpha1
kind: Theme
metadata:
  name: theme-material
spec:
  displayName: Material
  author:
    name: Anye
    website: https://www.anye.xyz
  description: 基于 Material Design 3 的 Halo 主题
  logo: "https://www.anye.xyz/logo"
  homepage: "https://github.com/Anyexyz/theme-material#readme"
  repo: "https://github.com/Anyexyz/theme-material"
  issues: "https://github.com/Anyexyz/theme-material/issues"
  settingName: "theme-material-setting"
  configMapName: "theme-material-configMap"
  version: "1.0.0"
  requires: ">=2.19.0"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/Anyexyz/theme-material/blob/main/LICENSE"
